[project]
name = "ligand-identification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.3.1",
    "streamlit>=1.50.0",
]
