defaults:
  - model: e3nn
  - machine: hpc
  - _self_

train:
  epochs: 100
  learning_rate: 1e-3
  out_channels: 219
  normalize_data: true
  weight_decay: 1e-4
  early_stopping:
    patience: 15
    mode: min
    monitor: val_loss

test:
  checkpoint_path: model.ckpt
  verbose: true

paths:
  train_data: data/processed_cryoem/train
  val_data: data/processed_cryoem/val
  test_data: testset
  model_checkpoint: checkpoints/

random_seed: 42